### ISSUE TITLE
Add automated build as a quality gate

### ISSUE THREAD

**Issue by flyhard** [tkmgo/haproxyconfigparser#4]
We already have a configuration for CircleCi, so I suggest that you set up a automated build with them and change the Badge in the Readme to it. You can set it up so it will build every pull request as well.

**Comment by takumakanari** [comment]
Sounds good.
I'll handle it later.

**Comment by takumakanari** [comment]
it seems that we already have build jobs in CircleCi.
@flyhard Do we still have any other tasks for this issue??

**Comment by flyhard** [comment]
I could not see the builds. I have set up some from my fork, but they cannot include the main repo...

**Comment by takumakanari** [comment]
Ah, I see.

I configured it again. Could you confirm it?

**Comment by flyhard** [comment]
I can. Looks good.

**Comment by takumakanari** [comment]
Thank you.
